#!/usr/bin/env python3
"""
build_fxr90_rest_api.py
========================
Build ``RestAPI/FXR90-rest-api.yaml`` for Swagger UI by combining:

 * **Schemas + operation metadata** from ``RestDeveloperfile.yaml`` (repo root)
 * **Rich operation descriptions** from ``RestAPI/operation_descriptions/*.md``

Run whenever ``RestDeveloperfile.yaml`` changes:

    python RestAPI/scripts/build_fxr90_rest_api.py

Do not edit ``FXR90-rest-api.yaml`` by hand — it is generated.
"""
from __future__ import annotations

import copy
import re
import sys
from collections import OrderedDict
from pathlib import Path

import yaml

OPENAPI_VERSION = "3.1.0"

REST_DIR = Path(__file__).resolve().parent.parent
ROOT = REST_DIR.parent
DEVELOPER_SPEC = ROOT / "RestDeveloperfile.yaml"
BUNDLED_OUT = REST_DIR / "FXR90-rest-api.yaml"
OP_DESCRIPTIONS_DIR = REST_DIR / "operation_descriptions"
AUTO_HEADER = (
    "# AUTO-GENERATED by RestAPI/scripts/build_fxr90_rest_api.py — do not edit.\n"
    "# Source schema: RestDeveloperfile.yaml\n"
    "# Descriptions: RestAPI/operation_descriptions/*.md\n"
    "# Rebuild: python RestAPI/scripts/build_fxr90_rest_api.py\n"
)

HTTP_METHODS = frozenset({"get", "put", "post", "delete", "patch", "head", "options", "trace"})

VENDOR_EXTENSION_PREFIX = "x-"
SCHEMA_DOC_STRIP_KEYS = frozenset({"example", "examples", "x-examples"})


def _represent_ordereddict(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


# The whole document is built from OrderedDicts to hold key order; without this
# SafeDumper refuses to serialize them.
yaml.add_representer(OrderedDict, _represent_ordereddict)
yaml.SafeDumper.add_representer(OrderedDict, _represent_ordereddict)


# --- Markdown operation descriptions ----------------------------------------------

_INTERNAL_NOTE_RE = re.compile(
    r"^\s*[-*]?\s*Keep REST behavior aligned with the documented reader workflow\.?\s*$",
    re.MULTILINE | re.IGNORECASE,
)
_PERFORM_BULLET_RE = re.compile(
    r"^\s*[-*]?\s*Perform the operation through the REST API using bearer-token authentication\.?\s*$",
    re.MULTILINE | re.IGNORECASE,
)
_BOILERPLATE_USE_BLOCK = re.compile(
    r"\n\*{0,2}Use this endpoint to:\*{0,2}\n\n(?:- .+\n)+",
    re.MULTILINE,
)
_SCHEMA_REVIEW_RE = re.compile(
    r"^\s*Review the request and response schemas in the REST API reference for required fields, optional fields, enum values, and examples before calling this endpoint\.?\s*$",
    re.MULTILINE | re.IGNORECASE,
)


def sanitize_operation_description(text: str) -> str:
    text = _INTERNAL_NOTE_RE.sub("", text)
    text = _PERFORM_BULLET_RE.sub("", text)
    text = _SCHEMA_REVIEW_RE.sub("", text)
    text = _BOILERPLATE_USE_BLOCK.sub("\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return f"{text}\n" if text else ""


def load_rest_operation_descriptions() -> dict[str, str]:
    descriptions: dict[str, str] = {}
    if not OP_DESCRIPTIONS_DIR.is_dir():
        return descriptions
    for path in sorted(OP_DESCRIPTIONS_DIR.iterdir()):
        if path.suffix.lower() != ".md" or path.name.lower() == "readme.md":
            continue
        if path.name.startswith("_"):
            continue
        text = sanitize_operation_description(path.read_text(encoding="utf-8-sig").strip())
        if text:
            descriptions[path.stem] = text
    return descriptions


def description_key(method: str, api_path: str, operation_id: str | None) -> str:
    if operation_id:
        return operation_id
    safe = api_path.strip("/").replace("/", "__")
    return f"{method.upper()}__{safe}"


# --- Schema helpers ----------------------------------------------------------------

def collect_refs(node, out) -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str) and value.startswith("#/components/schemas/"):
                out.add(value.split("/")[-1])
            else:
                collect_refs(value, out)
    elif isinstance(node, list):
        for value in node:
            collect_refs(value, out)


def _is_schema_object(node: dict) -> bool:
    if "$ref" in node:
        return True
    return any(
        key in node
        for key in ("type", "properties", "items", "oneOf", "anyOf", "allOf", "enum")
    )


def _fix_tag_metadata_items(obj: dict) -> dict:
    """Rewrite a type-array item (string|object) into an explicit oneOf."""
    items = obj.get("items")
    if not isinstance(items, dict):
        return obj
    if not isinstance(items.get("type"), list):
        return obj
    if "enum" not in items or "properties" not in items:
        return obj

    enum_vals = items.pop("enum")
    props = items.pop("properties")
    items.pop("type", None)
    items.clear()
    items["oneOf"] = [
        OrderedDict([("type", "string"), ("enum", enum_vals)]),
        OrderedDict([("type", "object"), ("properties", props)]),
    ]
    return obj


def _fix_malformed_selects(obj: dict) -> dict:
    """Give each `selects` oneOf branch an explicit `type: array`."""
    selects = obj.get("selects")
    if not isinstance(selects, dict):
        return obj
    if selects.get("type") != "array" or not isinstance(selects.get("oneOf"), list):
        return obj

    one_of = []
    for branch in selects["oneOf"]:
        if isinstance(branch, dict) and "items" in branch and "type" not in branch:
            one_of.append(OrderedDict([("type", "array"), ("items", branch["items"])]))
        else:
            one_of.append(branch)

    rebuilt = OrderedDict()
    if "description" in selects:
        rebuilt["description"] = selects["description"]
    rebuilt["oneOf"] = one_of
    obj["selects"] = rebuilt
    return obj


def _strip_schema_doc_noise(obj):
    if isinstance(obj, dict):
        obj = OrderedDict(obj)
        for key in list(obj.keys()):
            if key in SCHEMA_DOC_STRIP_KEYS or (
                isinstance(key, str) and key.startswith(VENDOR_EXTENSION_PREFIX)
            ):
                obj.pop(key, None)
        for key, value in obj.items():
            obj[key] = _strip_schema_doc_noise(value)
        return obj
    if isinstance(obj, list):
        return [_strip_schema_doc_noise(item) for item in obj]
    return obj


def sanitize_for_swagger_ui(doc: dict) -> dict:
    """Drop schema-level examples and x-* keys.

    Only descends into ``schema`` under a media type, so the interactive
    request-body/response ``examples`` sit outside its reach and survive.
    """
    components = doc.get("components")
    if isinstance(components, dict) and isinstance(components.get("schemas"), dict):
        schemas = components["schemas"]
        for name in list(schemas):
            schemas[name] = _strip_schema_doc_noise(schemas[name])

    for path_item in (doc.get("paths") or {}).values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            bodies = [operation.get("requestBody")]
            bodies.extend((operation.get("responses") or {}).values())
            for body in bodies:
                if not isinstance(body, dict):
                    continue
                for media in (body.get("content") or {}).values():
                    if isinstance(media, dict) and "schema" in media:
                        media["schema"] = _strip_schema_doc_noise(media["schema"])
    return doc


def fix_delete_request_bodies(paths: dict, schemas: dict | None = None) -> int:
    """A DELETE must not carry a body; move its properties to query parameters."""
    schemas = schemas or {}
    fixed = 0

    for path_item in paths.values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method != "delete" or not isinstance(operation, dict):
                continue
            if "requestBody" not in operation:
                continue

            body = operation.get("requestBody", {})
            content = body.get("content", {}) if isinstance(body, dict) else {}
            json_content = content.get("application/json", {})
            schema = json_content.get("schema", {}) if isinstance(json_content, dict) else {}

            if isinstance(schema, dict) and "$ref" in schema:
                ref = schema["$ref"]
                if ref.startswith("#/components/schemas/"):
                    schema = schemas.get(ref.rsplit("/", 1)[-1], schema)

            props = schema.get("properties", {}) if isinstance(schema, dict) else {}
            if not isinstance(props, dict) or not props:
                operation.pop("requestBody", None)
                fixed += 1
                continue

            params = list(operation.get("parameters") or [])
            existing = {(p.get("in"), p.get("name")) for p in params if isinstance(p, dict)}
            for prop_name, prop_schema in props.items():
                if ("query", prop_name) in existing or ("path", prop_name) in existing:
                    continue
                params.append(
                    OrderedDict(
                        [
                            ("name", prop_name),
                            ("in", "query"),
                            ("required", prop_name in (schema.get("required") or [])),
                            ("schema", prop_schema if isinstance(prop_schema, dict) else OrderedDict()),
                        ]
                    )
                )
            operation["parameters"] = params
            operation.pop("requestBody", None)
            fixed += 1
    return fixed

# Fallback when RestDeveloperfile omits operationId (path+method -> markdown stem).
# Only list entries that cannot be resolved via operationId + case-insensitive match.
PATH_METHOD_ALIASES: dict[tuple[str, str], str] = {
    ("GET", "/cloud/preSelection"): "getPreSelection",
    ("PUT", "/cloud/preSelection"): "setPreSelection",
    ("PUT", "/cloud/updatePassword"): "updatePassword",
    # Reserved for when developer restores missing /cloud/logs in RestDeveloperfile.yaml
    ("GET", "/cloud/logs"): "getLogs",
    ("PUT", "/cloud/logs"): "setLogs",
    ("GET", "/cloud/gpo"): "getGpoStatus",
    ("GET", "/cloud/eSimConfig"): "getEsimConfig",
    ("GET", "/cloud/logs/syslog"): "getLogsSyslog",
    ("DELETE", "/cloud/logs/syslog"): "delLogsSyslog",
    ("GET", "/cloud/logs/RcLog"): "getRcLog",
    ("GET", "/cloud/logs/RgWarningLog"): "getRgWarningLog",
    ("GET", "/cloud/logs/RgErrorLog"): "getRgErrorLog",
    ("GET", "/cloud/logs/radioPacketLog"): "getRadioPacketLog",
    ("DELETE", "/cloud/logs/radioPacketLog"): "delRadioPacketLog",
    ("GET", "/cloud/ntpServer"): "getNtpServer",
}


def normalize_for_oas31(obj):
    """Structural fixups, keeping OpenAPI 3.1 / JSON-Schema-2020-12 constructs.

    ``type: 'null'``, type arrays, and numeric ``exclusiveMinimum`` /
    ``exclusiveMaximum`` are preserved -- rewriting them for OAS 3.0 is what made
    ``PUT /cloud/config`` fail validation.

    Schema-level ``example``/``examples`` are dropped. The ``_is_schema_object``
    guard means media-type objects are not schema objects, so request-body and
    response examples survive untouched.
    """
    if isinstance(obj, dict):
        obj = OrderedDict(obj)

        if _is_schema_object(obj):
            obj.pop("example", None)
            obj.pop("examples", None)

        enum_val = obj.get("enum")
        if isinstance(enum_val, list):
            deduped = []
            for item in enum_val:
                if item not in deduped:
                    deduped.append(item)
            obj["enum"] = deduped

        obj = _fix_tag_metadata_items(obj)
        obj = _fix_malformed_selects(obj)

        for key, value in obj.items():
            obj[key] = normalize_for_oas31(value)
        return obj

    if isinstance(obj, list):
        return [normalize_for_oas31(item) for item in obj]
    return obj


def normalize_openapi_31(doc: dict) -> dict:
    doc = normalize_for_oas31(doc)
    doc = sanitize_for_swagger_ui(doc)
    doc["openapi"] = OPENAPI_VERSION
    schemas = doc.get("components", {}).get("schemas", {})
    if isinstance(doc.get("paths"), dict):
        fix_delete_request_bodies(doc["paths"], schemas if isinstance(schemas, dict) else None)
    return doc


def _component_base(method: str, api_path: str, operation: dict) -> str:
    """Component-name stem for an operation: operationId with a capital first letter.

    Only the leading character is changed, so getGPIStatus -> GetGPIStatus. Falls
    back to the markdown alias for the operations the developer file leaves without
    an operationId (GET /cloud/gpo and friends).
    """
    stem = operation.get("operationId") or PATH_METHOD_ALIASES.get((method.upper(), api_path))
    if not stem:
        stem = description_key(method, api_path, None)
    return stem[:1].upper() + stem[1:]


def hoist_operation_bodies(paths: dict, schemas: OrderedDict) -> int:
    """Move inline request/response schemas into named components.

    ``PUT /cloud/app-led`` gains ``SetAppledRequest`` / ``SetAppledResponse``; a
    second response code appends its status (``SetImpinjGen2XResponse422``). Schemas
    already expressed as a ``$ref`` are left alone -- notably ``GET /cloud/mode``,
    which the developer deliberately wired to ``operatingMode.v1``.
    """
    hoisted = OrderedDict()

    def take(media: dict, name: str) -> bool:
        schema = media.get("schema")
        if not isinstance(schema, dict) or "$ref" in schema:
            return False
        while name in schemas or name in hoisted:
            name += "_"
        hoisted[name] = schema
        media["schema"] = OrderedDict([("$ref", f"#/components/schemas/{name}")])
        return True

    count = 0
    for api_path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            base = _component_base(method, api_path, operation)

            body = operation.get("requestBody")
            if isinstance(body, dict):
                media = (body.get("content") or {}).get("application/json")
                if isinstance(media, dict) and take(media, f"{base}Request"):
                    count += 1

            for code, response in (operation.get("responses") or {}).items():
                if not isinstance(response, dict):
                    continue
                media = (response.get("content") or {}).get("application/json")
                if not isinstance(media, dict):
                    continue
                suffix = "" if str(code).startswith("2") else str(code)
                if take(media, f"{base}Response{suffix}"):
                    count += 1

    schemas.update(hoisted)
    return count


def prune_unreachable_schemas(paths: dict, schemas: OrderedDict) -> list[str]:
    """Drop every schema the endpoints cannot reach.

    Roots are the schemas ``$ref``-ed from ``paths``; from there the walk follows
    ``$ref`` chains, so a schema pulled in only via another schema (select.v1 via
    operatingMode.v1, for example) is kept. Anything left over is dead weight the
    developer file carries but no endpoint exposes. Returns the dropped names.
    """
    edges: dict[str, set] = {}
    for name, body in schemas.items():
        seen: set = set()
        collect_refs(body, seen)
        edges[name] = seen

    reachable: set = set()
    pending: set = set()
    collect_refs(paths, pending)

    while pending:
        name = pending.pop()
        if name in reachable or name not in schemas:
            continue
        reachable.add(name)
        pending |= edges[name] - reachable

    dropped = [name for name in schemas if name not in reachable]
    for name in dropped:
        del schemas[name]
    return dropped


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def dump_yaml(path: Path, data: dict) -> None:
    with path.open("w", encoding="utf-8") as fh:
        fh.write(AUTO_HEADER)
        yaml.safe_dump(
            data,
            fh,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=4096,
        )


def case_insensitive_descriptions(descriptions: dict[str, str]) -> dict[str, str]:
    """Allow operationId / markdown filename casing differences."""
    out = dict(descriptions)
    for key, text in descriptions.items():
        out.setdefault(key.lower(), text)
    return out


def lookup_description(
    method: str,
    api_path: str,
    operation_id: str | None,
    descriptions: dict[str, str],
) -> str | None:
    candidates: list[str] = []
    alias = PATH_METHOD_ALIASES.get((method.upper(), api_path))
    if alias:
        candidates.append(alias)
    if operation_id:
        candidates.append(operation_id)
    candidates.append(description_key(method, api_path, operation_id))
    for key in candidates:
        if key in descriptions:
            return descriptions[key]
        lower = key.lower()
        if lower in descriptions:
            return descriptions[lower]
    return None


def apply_markdown_descriptions(
    paths: dict,
    descriptions: dict[str, str],
) -> tuple[int, list[str]]:
    applied = 0
    missing: list[str] = []
    for api_path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            md = lookup_description(method, api_path, operation.get("operationId"), descriptions)
            if md:
                operation["description"] = md
                applied += 1
            else:
                key = description_key(method, api_path, operation.get("operationId"))
                missing.append(f"{method.upper()} {api_path} ({key})")
    return applied, missing


def main() -> int:
    if not DEVELOPER_SPEC.is_file():
        print(f"Missing developer spec: {DEVELOPER_SPEC}", file=sys.stderr)
        return 1

    spec = load_yaml(DEVELOPER_SPEC)
    bundled = copy.deepcopy(spec)

    # Ensure OrderedDict-friendly top-level keys for stable output.
    out = OrderedDict()
    for key in ("openapi", "info", "externalDocs", "servers", "tags"):
        if key in bundled:
            out[key] = bundled[key]

    paths = bundled.get("paths", {})
    if not isinstance(paths, dict):
        print("Developer spec has no paths section.", file=sys.stderr)
        return 1

    descriptions = case_insensitive_descriptions(load_rest_operation_descriptions())
    desc_applied, desc_missing = apply_markdown_descriptions(paths, descriptions)
    out["paths"] = paths

    components = OrderedDict()
    src_components = bundled.get("components", {})
    if isinstance(src_components, dict):
        if "securitySchemes" in src_components:
            components["securitySchemes"] = src_components["securitySchemes"]
        schemas = OrderedDict(src_components.get("schemas", {}) or {})
    else:
        schemas = OrderedDict()

    # Emit the developer file's components verbatim. Nested sub-schemas stay inline
    # where the source declares them; hoisting them out would mint components the
    # source never defined (readerstats.v1Antennas, eventsConfig.v1ErrorsCpu, ...).
    components["schemas"] = schemas
    out["components"] = components

    out = normalize_openapi_31(out)

    # Normalization rebuilds the dicts, so re-bind before pruning. This must run
    # after fix_delete_request_bodies, which can strip a DELETE body and with it
    # the only reference to a schema.
    schemas = out["components"]["schemas"]
    schema_count_in = len(schemas)
    hoisted = hoist_operation_bodies(out.get("paths", {}), schemas)
    dropped = prune_unreachable_schemas(out.get("paths", {}), schemas)

    dump_yaml(BUNDLED_OUT, out)

    declared = set(schemas.keys())
    used: set = set()
    collect_refs(out.get("paths", {}), used)
    collect_refs(schemas, used)
    missing_refs = sorted(used - declared)
    op_count = sum(
        1
        for path_item in paths.values()
        if isinstance(path_item, dict)
        for m in path_item
        if m in HTTP_METHODS
    )

    print(f"Source spec     : {DEVELOPER_SPEC.relative_to(REST_DIR.parent)}")
    print(f"Paths           : {len(paths)}")
    print(f"Operations      : {op_count}")
    print(f"Schemas         : {len(schemas)} ({schema_count_in} in source + {hoisted} hoisted - {len(dropped)} pruned)")
    print(f"Op docs applied : {desc_applied} / {op_count}")
    print(f"Hoisted         : {hoisted} inline body/response schema(s) -> named components")
    print(f"Pruned          : {len(dropped)} schema(s) no endpoint can reach")
    print(f"Output          : {BUNDLED_OUT.relative_to(REST_DIR.parent)}")

    if dropped:
        print("\nDropped (unreachable from any endpoint):")
        for name in dropped:
            print(f"  - {name}")

    if desc_missing:
        print(f"\nNo markdown description ({len(desc_missing)} operation(s)):")
        for line in desc_missing[:15]:
            print(f"  {line}")
        if len(desc_missing) > 15:
            print(f"  ... and {len(desc_missing) - 15} more")

    if missing_refs:
        print("\nBROKEN REFERENCES (no matching schema):")
        for name in missing_refs:
            print(f"  #/components/schemas/{name}")
        return 1

    print("Reference check : OK")
    try:
        from openapi_spec_validator import validate as _validate  # type: ignore

        _validate(load_yaml(BUNDLED_OUT))
        print("openapi-spec-validator: VALID")
    except ImportError:
        print("openapi-spec-validator: not installed (skipped)")
    except Exception as exc:  # noqa: BLE001
        print(f"openapi-spec-validator: ISSUES -> {exc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
