#!/usr/bin/env python3
"""
FXR_60-90_api_scalar.py
=======================
Build ``rest/FXR_60-90_scalar_api.yaml`` for Scalar without changing the Swagger UI pipeline.

Same schemas, examples, and Swagger markdown as ``FXR_60-90_api_rest_api.py``, then:

 * Overlay ``rest/scalar/info.md`` onto ``info.description``
 * Overlay ``rest/scalar/operation_descriptions/*.md`` onto matching operationIds
 * Strip heading numbers (``## 1. Description`` → ``## Description``)
 * Add a ``servers`` placeholder so the user can enter the reader address

Run:

    python rest/scripts/FXR_60-90_api_scalar.py

Do not edit ``FXR_60-90_scalar_api.yaml`` by hand — it is generated.
Do not run this instead of the Swagger build; it writes a different output file.
"""
from __future__ import annotations

import copy
import importlib.util
import re
import sys
from collections import OrderedDict
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = Path(__file__).resolve().parent
ROOT = PACKAGE_DIR.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from build_fxr90_rest_api import (  # type: ignore  # noqa: E402
    HTTP_METHODS,
    _YAML11_AMBIGUOUS_STR,
    apply_markdown_descriptions,
    case_insensitive_descriptions,
    collect_refs,
    hoist_operation_bodies,
    load_yaml,
    normalize_openapi_31,
    prune_unreachable_schemas,
)

_rest_spec = importlib.util.spec_from_file_location(
    "fxr_rest_build",
    SCRIPTS_DIR / "FXR_60-90_api_rest_api.py",
)
fxr_rest = importlib.util.module_from_spec(_rest_spec)
assert _rest_spec.loader is not None
_rest_spec.loader.exec_module(fxr_rest)

OPENAPI_VERSION = "3.1.1"
SCALAR_DIR = PACKAGE_DIR / "scalar"
SCALAR_INFO = SCALAR_DIR / "info.md"
SCALAR_OP_DIR = SCALAR_DIR / "operation_descriptions"
BUNDLED_OUT = PACKAGE_DIR / "FXR_60-90_scalar_api.yaml"

AUTO_HEADER = (
    "# AUTO-GENERATED by rest/scripts/FXR_60-90_api_scalar.py — do not edit.\n"
    "# Scalar Galaxy YAML format (description: |, indented lists, OpenAPI 3.1.1).\n"
    "# Rebuild: python rest/scripts/FXR_60-90_api_scalar.py\n"
)


def _represent_ordereddict(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


def _represent_str_literal(dumper, data):
    """Match Scalar Galaxy: multiline strings as `|`, $ref values double-quoted."""
    text = data.replace("\r\n", "\n").replace("\r", "\n")
    if "\n" in text:
        if not text.endswith("\n"):
            text += "\n"
        return dumper.represent_scalar("tag:yaml.org,2002:str", text, style="|")
    if text.startswith("#/") or ("{" in text and "}" in text) or _YAML11_AMBIGUOUS_STR.match(text):
        return dumper.represent_scalar("tag:yaml.org,2002:str", text, style='"')
    return dumper.represent_scalar("tag:yaml.org,2002:str", text)


def dump_yaml(path: Path, data: dict) -> None:
    import yaml

    class _ScalarDumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    _ScalarDumper.add_representer(OrderedDict, _represent_ordereddict)
    _ScalarDumper.add_representer(dict, _represent_ordereddict)
    _ScalarDumper.add_representer(str, _represent_str_literal)

    with path.open("w", encoding="utf-8") as fh:
        fh.write(AUTO_HEADER)
        yaml.dump(
            data,
            fh,
            Dumper=_ScalarDumper,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=4096,
        )


# ``## 1. Description`` → ``## Description``. Leaves ``802.1X`` headings alone.
_HEADING_NUMBER_RE = re.compile(r"^(#{1,6})\s+\d{1,2}\.\s+([A-Za-z].*)$", re.MULTILINE)


def strip_heading_numbers(text: str) -> str:
    return _HEADING_NUMBER_RE.sub(r"\1 \2", text)


def load_scalar_markdown(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig").strip() + "\n"


def load_scalar_operation_overlays() -> dict[str, str]:
    overlays: dict[str, str] = {}
    if not SCALAR_OP_DIR.is_dir():
        return overlays
    for path in sorted(SCALAR_OP_DIR.iterdir()):
        if path.suffix.lower() != ".md" or path.name.lower() == "readme.md":
            continue
        if path.name.startswith("_"):
            continue
        text = load_scalar_markdown(path)
        if text.strip():
            overlays[path.stem] = text
    return overlays


SCALAR_SERVERS = [
    OrderedDict(
        [
            ("url", "https://YOUR_READER_IP"),
            (
                "description",
                "Replace YOUR_READER_IP with the reader IP address or hostname.",
            ),
        ]
    ),
    OrderedDict(
        [
            ("url", "http://YOUR_READER_IP"),
            ("description", "Use HTTP if HTTPS is not enabled on the reader."),
        ]
    ),
]

SCALAR_ENVIRONMENTS = OrderedDict(
    [
        (
            "Reader",
            OrderedDict(
                [
                    ("description", "FXR reader"),
                    (
                        "variables",
                        OrderedDict(
                            [
                                (
                                    "baseUrl",
                                    OrderedDict(
                                        [
                                            (
                                                "description",
                                                "Reader address",
                                            ),
                                            (
                                                "default",
                                                "https://YOUR_READER_IP",
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
)


def brand_info_for_scalar(info) -> OrderedDict:
    branded = fxr_rest.brand_info_for_fxr_60_90(info)
    if SCALAR_INFO.is_file():
        branded["description"] = load_scalar_markdown(SCALAR_INFO)
    branded["title"] = "IoT Connector REST API (FXR readers)"
    return branded


def main() -> int:
    if not fxr_rest.DEVELOPER_SPEC.is_file():
        print(f"Missing developer spec: {fxr_rest.DEVELOPER_SPEC}", file=sys.stderr)
        return 1

    import build_fxr90_rest_api  # noqa: F401

    spec = load_yaml(fxr_rest.DEVELOPER_SPEC)
    bundled = copy.deepcopy(spec)

    out = OrderedDict()
    for key in ("openapi", "info", "externalDocs"):
        if key in bundled:
            out[key] = bundled[key]
    out["info"] = brand_info_for_scalar(out.get("info"))
    out["servers"] = copy.deepcopy(SCALAR_SERVERS)
    out["x-scalar-environments"] = copy.deepcopy(SCALAR_ENVIRONMENTS)
    if "tags" in bundled:
        out["tags"] = bundled["tags"]

    paths = bundled.get("paths", {})
    if not isinstance(paths, dict):
        print("Developer spec has no paths section.", file=sys.stderr)
        return 1

    descriptions = case_insensitive_descriptions(fxr_rest.load_package_operation_descriptions())
    overlays = load_scalar_operation_overlays()
    descriptions.update(case_insensitive_descriptions(overlays))
    descriptions = {key: strip_heading_numbers(text) for key, text in descriptions.items()}
    desc_applied, desc_missing = apply_markdown_descriptions(paths, descriptions)

    stripped = fxr_rest.strip_all_yaml_examples(paths)
    ex_ops, ex_blocks, ex_missing = fxr_rest.apply_reviewed_examples(paths)

    out["paths"] = paths

    components = OrderedDict()
    src_components = bundled.get("components", {})
    if isinstance(src_components, dict):
        if "securitySchemes" in src_components:
            components["securitySchemes"] = src_components["securitySchemes"]
        schemas = OrderedDict(src_components.get("schemas", {}) or {})
    else:
        schemas = OrderedDict()

    components["schemas"] = schemas
    out["components"] = components

    out = normalize_openapi_31(out)
    out["openapi"] = OPENAPI_VERSION

    schemas = out["components"]["schemas"]
    schema_count_in = len(schemas)
    hoisted = hoist_operation_bodies(out.get("paths", {}), schemas)
    dropped = prune_unreachable_schemas(out.get("paths", {}), schemas)

    dump_yaml(BUNDLED_OUT, out)

    declared = set(schemas.keys())
    used: set = set()
    collect_refs(out.get("paths", {}), used)
    collect_refs(schemas, used)
    missing_refs = sorted(used - declared)
    op_count = sum(
        1
        for path_item in paths.values()
        if isinstance(path_item, dict)
        for m in path_item
        if m in HTTP_METHODS
    )

    print(f"Package         : {PACKAGE_DIR.relative_to(ROOT)}")
    print(f"Source spec     : {fxr_rest.DEVELOPER_SPEC.relative_to(ROOT)}")
    print(f"Scalar overlays : {len(overlays)} ({', '.join(sorted(overlays)) or 'none'})")
    print(f"Scalar info     : {SCALAR_INFO.relative_to(ROOT) if SCALAR_INFO.is_file() else 'missing'}")
    print(f"Paths           : {len(paths)}")
    print(f"Operations      : {op_count}")
    print(
        f"Schemas         : {len(schemas)} "
        f"({schema_count_in} in source + {hoisted} hoisted - {len(dropped)} pruned)"
    )
    packs = fxr_rest.count_example_packs()
    print(f"Op docs applied : {desc_applied} / {op_count}")
    print(f"YAML examples   : stripped {stripped} media-type example/examples key(s)")
    print(f"Op examples     : {ex_ops} / {op_count} operation(s), {ex_blocks} media block(s) from folder packs only")
    print(f"Example packs   : {packs} under {fxr_rest.OP_EXAMPLES_DIR.relative_to(ROOT)}")
    print(f"Hoisted         : {hoisted} inline body/response schema(s) -> named components")
    print(f"Pruned          : {len(dropped)} schema(s) no endpoint can reach")
    print(f"Output (Scalar) : {BUNDLED_OUT.relative_to(ROOT)}")

    if dropped:
        print("\nDropped (unreachable from any endpoint):")
        for name in dropped:
            print(f"  - {name}")

    if desc_missing:
        print(f"\nNo markdown description ({len(desc_missing)} operation(s)):")
        for line in desc_missing[:15]:
            print(f"  {line}")
        if len(desc_missing) > 15:
            print(f"  ... and {len(desc_missing) - 15} more")

    if ex_missing:
        print(f"\nNo JSON examples ({len(ex_missing)} operation(s) - no examples in output):")
        for line in ex_missing[:15]:
            print(f"  {line}")
        if len(ex_missing) > 15:
            print(f"  ... and {len(ex_missing) - 15} more")
        return 1

    if missing_refs:
        print("\nBROKEN REFERENCES (no matching schema):")
        for name in missing_refs:
            print(f"  #/components/schemas/{name}")
        return 1

    print("Reference check : OK")
    try:
        from openapi_spec_validator import validate as _validate  # type: ignore

        _validate(load_yaml(BUNDLED_OUT))
        print("openapi-spec-validator: VALID")
    except ImportError:
        print("openapi-spec-validator: not installed (skipped)")
    except Exception as exc:  # noqa: BLE001
        print(f"openapi-spec-validator: ISSUES -> {exc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
