#!/usr/bin/env python3
"""
FXR_60-90_api_rest_api.py
=========================
Build the **final** ``FXR60-90/rest/FXR_60-90_rest_api.yaml`` for Swagger UI by combining:

 * **Schemas + operation metadata** from ``RestDeveloperfile.yaml`` (this package)
 * **Rich operation descriptions** from ``operation_descriptions/*.md``
 * **Request/response examples** from ``operation_examples/<path>/<METHOD>/*.json``

Run:

    python FXR60-90/rest/scripts/FXR_60-90_api_rest_api.py

Do not edit ``FXR_60-90_rest_api.yaml`` by hand — it is generated.
"""
from __future__ import annotations

import copy
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent.parent  # FXR60-90/rest
SCRIPTS_DIR = Path(__file__).resolve().parent
ROOT = PACKAGE_DIR.parent.parent  # repo root (optional; package is self-contained)
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from build_fxr90_rest_api import (  # type: ignore  # noqa: E402
    HTTP_METHODS,
    PATH_METHOD_ALIASES,
    apply_markdown_descriptions,
    case_insensitive_descriptions,
    collect_refs,
    description_key,
    hoist_operation_bodies,
    load_yaml,
    normalize_openapi_31,
    prune_unreachable_schemas,
    sanitize_operation_description,
)

OPENAPI_VERSION = "3.1.0"

DEVELOPER_SPEC = PACKAGE_DIR / "RestDeveloperfile.yaml"
BUNDLED_OUT = PACKAGE_DIR / "FXR_60-90_rest_api.yaml"
OP_DESCRIPTIONS_DIR = PACKAGE_DIR / "operation_descriptions"
OP_EXAMPLES_DIR = PACKAGE_DIR / "operation_examples"

AUTO_HEADER = (
    "# AUTO-GENERATED by FXR60-90/rest/scripts/FXR_60-90_api_rest_api.py — do not edit.\n"
    "# Final FXR60 / FXR90 REST API for Swagger UI.\n"
    "# Source schema: FXR60-90/rest/RestDeveloperfile.yaml\n"
    "# Descriptions: FXR60-90/rest/operation_descriptions/*.md\n"
    "# Examples: FXR60-90/rest/operation_examples/<path>/<METHOD>/*.json\n"
    "# Rebuild: python FXR60-90/rest/scripts/FXR_60-90_api_rest_api.py\n"
)

INFO_PRODUCT_LINE = (
    "# Overview\n"
    "\n"
    "This REST API controls Zebra **FXR** RFID readers. FXR documentation includes **FXR60** and **FXR90**.\n"
    "The definition can be found below.\n"
    "\n"
    "# Authentication\n"
    "\n"
    "If a bearer token has already been copied from the dashboard page, use it in `Authorize` > bearerAuth.\n"
    "If not, enter Admin login credentials in `Authorize` > basicAuth, execute `/cloud/localRestLogin`,\n"
    "and copy the bearer token from the response into `Authorize` > bearerAuth.\n"
)


def dump_yaml(path: Path, data: dict) -> None:
    import yaml

    with path.open("w", encoding="utf-8") as fh:
        fh.write(AUTO_HEADER)
        yaml.safe_dump(
            data,
            fh,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=4096,
        )


def load_package_operation_descriptions() -> dict[str, str]:
    descriptions: dict[str, str] = {}
    if not OP_DESCRIPTIONS_DIR.is_dir():
        return descriptions
    for path in sorted(OP_DESCRIPTIONS_DIR.iterdir()):
        if path.suffix.lower() != ".md" or path.name.lower() == "readme.md":
            continue
        if path.name.startswith("_"):
            continue
        text = sanitize_operation_description(path.read_text(encoding="utf-8-sig").strip())
        if text:
            descriptions[path.stem] = text
    return descriptions


# --- Reviewed-by-me operation examples -------------------------------------------

def path_slug(api_path: str) -> str:
    s = api_path.strip("/").replace("{", "").replace("}", "")
    return re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()


def _example_entry(value, summary: str = "", example_name: str = "") -> OrderedDict:
    text = (summary or "").strip() or (example_name or "example").replace("_", " ")
    return OrderedDict([("summary", text), ("value", value)])

def _parse_summaries_md(endpoint_dir: Path) -> dict[str, dict]:
    """Parse SUMMARIES.md → relative file path -> {example_name, summary, code?}."""
    path = endpoint_dir / "SUMMARIES.md"
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8-sig")
    out: dict[str, dict] = {}
    # Split on ### headings so optional HTTP status cannot leak across blocks.
    chunks = re.split(r"(?m)^###\s+", text)
    for chunk in chunks[1:]:
        file_match = re.match(r"`(?P<file>[^`]+)`", chunk)
        if not file_match:
            continue
        rel = file_match.group("file").replace("\\", "/")
        name_match = re.search(r"\*\*Example name\*\*\s*\|\s*`(?P<name>[^`]+)`", chunk)
        summary_match = re.search(r"\*\*Summary title\*\*\s*\|\s*`(?P<summary>[^`]+)`", chunk)
        code_match = re.search(r"\*\*HTTP status\*\*\s*\|\s*`(?P<code>[^`]+)`", chunk)
        if not name_match or not summary_match:
            continue
        item = {
            "example_name": name_match.group("name"),
            "summary": summary_match.group("summary"),
        }
        if code_match:
            item["code"] = code_match.group("code")
        out[rel] = item
    return out


def _infer_direction(method: str, filename: str) -> tuple[str, str | None]:
    """Return (direction, status_code) using reviewed-by-me conventions."""
    stem = Path(filename).stem
    # Explicit response files under PUT/DELETE: response_200_default.json
    m = re.match(r"response[_-]?(\d{3})[_-]?(.*)", stem, re.IGNORECASE)
    if m:
        return "response", m.group(1)
    if method == "GET":
        return "response", "200"
    if method == "DELETE" and not stem.lower().startswith("request"):
        # Most DELETE examples here are empty success responses.
        return "response", "200"
    return "request", None


def _parse_manifest_direction(raw: str, method: str, filename: str) -> tuple[str, str | None]:
    """Parse direction values like ``response 200`` or ``request``."""
    text = (raw or "").strip().lower()
    if text.startswith("response"):
        parts = text.split()
        code = parts[1] if len(parts) > 1 and parts[1].isdigit() else "200"
        return "response", code
    if text.startswith("request"):
        return "request", None
    return _infer_direction(method, filename)


def _load_endpoint_examples(endpoint_dir: Path) -> list[dict]:
    """Load examples from SUMMARIES.md + METHOD/*.json (optional ``_manifest.json``)."""
    summaries = _parse_summaries_md(endpoint_dir)
    man_path = endpoint_dir / "_manifest.json"
    if man_path.is_file():
        try:
            data = json.loads(man_path.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            print(f"WARNING: invalid {man_path}: {exc}", file=sys.stderr)
            data = None
        if isinstance(data, list) and data:
            items: list[dict] = []
            for entry in data:
                if not isinstance(entry, dict):
                    continue
                rel = str(entry.get("file") or "").replace("\\", "/")
                if not rel or rel.endswith("parameters.json") or Path(rel).name == "parameters.json":
                    continue
                method = str(entry.get("method") or rel.split("/", 1)[0]).upper()
                direction, code = _parse_manifest_direction(
                    str(entry.get("direction") or ""), method, Path(rel).name
                )
                name = str(entry.get("example_name") or Path(rel).stem)
                # Prefer SUMMARIES.md titles when present; never keep audit-marker summaries.
                summary = str(
                    (summaries.get(rel) or {}).get("summary")
                    or entry.get("summary")
                    or ""
                ) or name.replace("_", " ")
                items.append(
                    {
                        "file": rel,
                        "method": method,
                        "direction": direction,
                        "code": code,
                        "example_name": name,
                        "summary": summary,
                    }
                )
            if items:
                return items

    items = []
    for method_dir in sorted(p for p in endpoint_dir.iterdir() if p.is_dir()):
        method = method_dir.name.upper()
        if method not in {m.upper() for m in HTTP_METHODS}:
            continue
        for jf in sorted(method_dir.glob("*.json")):
            if jf.name == "parameters.json":
                continue
            rel = f"{method}/{jf.name}"
            meta = summaries.get(rel, {})
            direction, code = _infer_direction(method, jf.name)
            if meta.get("code"):
                code = str(meta["code"])
                direction = "response"
            summary = str(meta.get("summary") or "")
            if summary.lower().startswith("response"):
                direction = "response"
                code = code or "200"
            elif summary.lower().startswith("request"):
                direction = "request"
                code = None
            items.append(
                {
                    "file": rel,
                    "method": method,
                    "direction": direction,
                    "code": code,
                    "example_name": str(meta.get("example_name") or jf.stem),
                    "summary": summary or jf.stem.replace("_", " "),
                }
            )
    return items


def load_examples_for_operation(api_path: str, method: str) -> dict | None:
    """Load reviewed-by-me examples for one path+method into OpenAPI inject shape."""
    endpoint_dir = OP_EXAMPLES_DIR / path_slug(api_path)
    if not endpoint_dir.is_dir():
        return None

    method_u = method.upper()
    catalog = [
        item
        for item in _load_endpoint_examples(endpoint_dir)
        if str(item.get("method", "")).upper() == method_u
    ]
    if not catalog:
        return None

    req_examples: OrderedDict = OrderedDict()
    resp_examples: dict[str, OrderedDict] = {}

    for item in catalog:
        rel = str(item.get("file") or "").replace("\\", "/")
        jf = endpoint_dir / rel
        if not jf.is_file():
            print(f"WARNING: missing example file {jf.relative_to(ROOT)}", file=sys.stderr)
            continue
        try:
            value = json.loads(jf.read_text(encoding="utf-8-sig"))
        except json.JSONDecodeError as exc:
            print(f"WARNING: invalid JSON {jf.name}: {exc}", file=sys.stderr)
            continue

        name = str(item.get("example_name") or jf.stem)
        summary = str(item.get("summary") or "")
        direction = str(item.get("direction") or "request").lower()
        entry = _example_entry(value, summary, name)
        if direction == "request":
            req_examples[name] = entry
        else:
            code = str(item.get("code") or "200")
            bucket = resp_examples.setdefault(code, OrderedDict())
            bucket[name] = entry

    payload: dict = {}
    if req_examples:
        payload["requestBody"] = {"application/json": req_examples}
    if resp_examples:
        payload["responses"] = {
            code: {"application/json": examples} for code, examples in resp_examples.items()
        }
    return payload or None


def count_example_packs() -> int:
    if not OP_EXAMPLES_DIR.is_dir():
        return 0
    return sum(1 for p in OP_EXAMPLES_DIR.iterdir() if p.is_dir() and not p.name.startswith("_"))


def strip_all_yaml_examples(paths: dict) -> int:
    """Remove every media-type example/examples so only folder JSON can supply them."""
    removed = 0
    for path_item in paths.values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            bodies = [operation.get("requestBody")]
            bodies.extend((operation.get("responses") or {}).values())
            for body in bodies:
                if not isinstance(body, dict):
                    continue
                for media in (body.get("content") or {}).values():
                    if not isinstance(media, dict):
                        continue
                    if "examples" in media:
                        media.pop("examples", None)
                        removed += 1
                    if "example" in media:
                        media.pop("example", None)
                        removed += 1
    return removed


def _set_media_examples(media: dict, examples: OrderedDict) -> None:
    """Attach pack examples to a media type.

    One example → media ``example`` (no Examples dropdown, so Swagger cannot
    invent ``[Modified value]``). Multiple → media ``examples`` map.
    """
    media.pop("example", None)
    media.pop("examples", None)
    if len(examples) == 1:
        only = next(iter(examples.values()))
        if isinstance(only, dict) and "value" in only:
            media["example"] = only["value"]
        else:
            media["example"] = only
        return
    media["examples"] = examples


def apply_reviewed_examples(paths: dict) -> tuple[int, int, list[str]]:
    """Inject examples from reviewed-by-me folders only."""
    applied_ops = 0
    applied_blocks = 0
    missing: list[str] = []

    for api_path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            payload = load_examples_for_operation(api_path, method)
            if not payload:
                key = description_key(method, api_path, operation.get("operationId"))
                missing.append(
                    f"{method.upper()} {api_path} ({key}) "
                    f"[expected folder {path_slug(api_path)}/{method.upper()}/]"
                )
                continue

            touched = False

            req_block = payload.get("requestBody")
            if isinstance(req_block, dict):
                for media_type, ex_map in req_block.items():
                    if not isinstance(ex_map, dict) or not ex_map:
                        continue
                    body = operation.setdefault("requestBody", OrderedDict())
                    if not isinstance(body, dict):
                        body = OrderedDict()
                        operation["requestBody"] = body
                    content = body.setdefault("content", OrderedDict())
                    if not isinstance(content, dict):
                        content = OrderedDict()
                        body["content"] = content
                    media = content.get(media_type)
                    if not isinstance(media, dict):
                        media = OrderedDict()
                        content[media_type] = media
                    _set_media_examples(media, OrderedDict(ex_map))
                    applied_blocks += 1
                    touched = True

            resp_block = payload.get("responses")
            if isinstance(resp_block, dict):
                responses = operation.setdefault("responses", OrderedDict())
                if not isinstance(responses, dict):
                    responses = OrderedDict()
                    operation["responses"] = responses
                for code, code_body in resp_block.items():
                    if not isinstance(code_body, dict):
                        continue
                    response = responses.get(str(code))
                    if not isinstance(response, dict):
                        response = OrderedDict([("description", str(code))])
                        responses[str(code)] = response
                    for media_type, ex_map in code_body.items():
                        if not isinstance(ex_map, dict) or not ex_map:
                            continue
                        content = response.setdefault("content", OrderedDict())
                        if not isinstance(content, dict):
                            content = OrderedDict()
                            response["content"] = content
                        media = content.get(media_type)
                        if not isinstance(media, dict):
                            media = OrderedDict()
                            content[media_type] = media
                        _set_media_examples(media, OrderedDict(ex_map))
                        applied_blocks += 1
                        touched = True

            if touched:
                applied_ops += 1

    return applied_ops, applied_blocks, missing


def brand_info_for_fxr_60_90(info) -> OrderedDict:
    """Title the shared FXR reader product line; list models in the description."""
    if not isinstance(info, dict):
        info = OrderedDict()
    else:
        info = OrderedDict(info)
    info["title"] = "IoT Connector REST API (FXR readers)"
    info["description"] = INFO_PRODUCT_LINE
    return info


def main() -> int:
    if not DEVELOPER_SPEC.is_file():
        print(f"Missing developer spec: {DEVELOPER_SPEC}", file=sys.stderr)
        return 1

    # Register OrderedDict YAML representer from the helper module.
    import build_fxr90_rest_api  # noqa: F401

    spec = load_yaml(DEVELOPER_SPEC)
    bundled = copy.deepcopy(spec)

    out = OrderedDict()
    for key in ("openapi", "info", "externalDocs", "servers", "tags"):
        if key in bundled:
            out[key] = bundled[key]
    out["info"] = brand_info_for_fxr_60_90(out.get("info"))

    paths = bundled.get("paths", {})
    if not isinstance(paths, dict):
        print("Developer spec has no paths section.", file=sys.stderr)
        return 1

    descriptions = case_insensitive_descriptions(load_package_operation_descriptions())
    desc_applied, desc_missing = apply_markdown_descriptions(paths, descriptions)

    # Examples come ONLY from FXR60-90/rest/operation_examples/<path>/<METHOD>/*.json.
    stripped = strip_all_yaml_examples(paths)
    ex_ops, ex_blocks, ex_missing = apply_reviewed_examples(paths)

    out["paths"] = paths

    components = OrderedDict()
    src_components = bundled.get("components", {})
    if isinstance(src_components, dict):
        if "securitySchemes" in src_components:
            components["securitySchemes"] = src_components["securitySchemes"]
        schemas = OrderedDict(src_components.get("schemas", {}) or {})
    else:
        schemas = OrderedDict()

    components["schemas"] = schemas
    out["components"] = components

    out = normalize_openapi_31(out)
    out["openapi"] = OPENAPI_VERSION

    schemas = out["components"]["schemas"]
    schema_count_in = len(schemas)
    hoisted = hoist_operation_bodies(out.get("paths", {}), schemas)
    dropped = prune_unreachable_schemas(out.get("paths", {}), schemas)

    dump_yaml(BUNDLED_OUT, out)

    declared = set(schemas.keys())
    used: set = set()
    collect_refs(out.get("paths", {}), used)
    collect_refs(schemas, used)
    missing_refs = sorted(used - declared)
    op_count = sum(
        1
        for path_item in paths.values()
        if isinstance(path_item, dict)
        for m in path_item
        if m in HTTP_METHODS
    )

    print(f"Package         : {PACKAGE_DIR.relative_to(ROOT)}")
    print(f"Source spec     : {DEVELOPER_SPEC.relative_to(ROOT)}")
    print(f"Paths           : {len(paths)}")
    print(f"Operations      : {op_count}")
    print(
        f"Schemas         : {len(schemas)} "
        f"({schema_count_in} in source + {hoisted} hoisted - {len(dropped)} pruned)"
    )
    packs = count_example_packs()
    print(f"Op docs applied : {desc_applied} / {op_count}")
    print(f"YAML examples   : stripped {stripped} media-type example/examples key(s)")
    print(f"Op examples     : {ex_ops} / {op_count} operation(s), {ex_blocks} media block(s) from folder packs only")
    print(f"Example packs   : {packs} under {OP_EXAMPLES_DIR.relative_to(ROOT)}")
    print(f"Hoisted         : {hoisted} inline body/response schema(s) -> named components")
    print(f"Pruned          : {len(dropped)} schema(s) no endpoint can reach")
    print(f"Output (final)  : {BUNDLED_OUT.relative_to(ROOT)}")

    if dropped:
        print("\nDropped (unreachable from any endpoint):")
        for name in dropped:
            print(f"  - {name}")

    if desc_missing:
        print(f"\nNo markdown description ({len(desc_missing)} operation(s)):")
        for line in desc_missing[:15]:
            print(f"  {line}")
        if len(desc_missing) > 15:
            print(f"  ... and {len(desc_missing) - 15} more")

    if ex_missing:
        print(f"\nNo JSON examples ({len(ex_missing)} operation(s) - no examples in output):")
        for line in ex_missing[:15]:
            print(f"  {line}")
        if len(ex_missing) > 15:
            print(f"  ... and {len(ex_missing) - 15} more")
        return 1

    if missing_refs:
        print("\nBROKEN REFERENCES (no matching schema):")
        for name in missing_refs:
            print(f"  #/components/schemas/{name}")
        return 1

    print("Reference check : OK")
    try:
        from openapi_spec_validator import validate as _validate  # type: ignore

        _validate(load_yaml(BUNDLED_OUT))
        print("openapi-spec-validator: VALID")
    except ImportError:
        print("openapi-spec-validator: not installed (skipped)")
    except Exception as exc:  # noqa: BLE001
        print(f"openapi-spec-validator: ISSUES -> {exc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
